"""
This module contains configuration for the Hargassner system.
"""

class HargConfig():
    """
    This class is for configuration
    all this is reusing the job of Jahislove (https://github.com/Jahislove) 
    @ https://github.com/Jahislove/Hargassner/tree/master
    """
    wanted: list[str] = [] #list of values wanted
    desc: dict = {} # dictonary describing the values
    map: dict = {} # map between order in pm buffer and value
    scan: int = 0 # scan interval in seconds for pm bufer

    def __init__(self):
        # setting a scan interval
        self.scan= 60
        # defining the list of value (from telnetproxy) we want to expose
#        self.wanted= [
#			 'c0', 'c1','c2','c3','c4','c5','c6','c7','c8','c9',
#			 'c10', 'c11','c12','c13','c14','c15','c16','c17','c18','c19',
#			 'c20', 'c21','c22','c23','c24','c25','c26','c27','c28','c29',
#			 'c30', 'c31','c32','c33','c34','c35','c36','c37','c38','c39',
#			 'c40', 'c41','c42','c43','c44','c45','c46','c47','c48','c49',
#			 'c50', 'c51','c52','c53','c54','c55','c56','c57','c58','c59',
#			 'c60', 'c61','c62','c63','c64','c65','c66','c67','c68','c69',
#			 'c70', 'c71','c72','c73','c74','c75','c76','c77','c78','c79',
#			 'c80', 'c81','c82','c83','c84','c85','c86','c87','c88','c89',
#			 'c90', 'c91','c92','c93','c94','c95','c96','c97','c98','c99'
#        ]
        self.wanted= [
            'MSG', 'TOKEN', 'KEY', 'UPTIME', 'SYS', 'BOOT', 'KT', 'IGW', 'SWV', 'FWV', 'SNIO', 'SNBCE', 'RTC',
	    'c0', 'c3', 'c5', 'c6', 'c7', 'c8', 'c9', 'c10', 'c21', 'c22', 'c27', 'c95', 'c96', 'c99', 'c115','c134', 'c138', 'c180'
        ]

        # explaining the values
        self.desc= {

'MSG':{'name':'Message',			'unit':'',		'desc':'message string'},
'KT':{'name':'KT',			'unit':'',		'desc':'kt string'},
'TOKEN':{'name':'Login token',			'unit':'',		'desc':'token string'},
'KEY':{'name':'Login key',			'unit':'',		'desc':'key string'},
'UPTIME':{'name':'UPTIME',			'unit':'',		'desc':'uptime'},
'SYS':{'name':'SYS',				'unit':'',		'desc':'Code system'},
'BOOT':{'name':'BOOT',				'unit':'',		'desc':'Boot version'},
'IGW':{'name':'IGW',				'unit':'',		'desc':'N° de série Passerelle'},
'SWV':{'name':'SWV',				'unit':'',		'desc':'Version logiciel'},
'FWV':{'name':'FWV',				'unit':'',		'desc':'Version firmware I/O'},
'SNIO':{'name':'SNIO',				'unit':'',		'desc':'N° de série I/O'},
'SNBCE':{'name':'SNBCE',			'unit':'',		'desc':'N° de série Pupitre'},
'RTC':{'name':'RTC',	    		        'unit':'',		'desc':'real time counter'},
'c0':{'name':'ZK',				'unit':'',		'desc':'etat chaudiere'},
'c1':{'name':'O2',				'unit':'%',	    'desc':'O2 est'},
'c2':{'name':'O2soll',			    'unit':'%',	    'desc':'O2 doit'},
'c3':{'name':'TK',				    'unit':'°C',	'desc':'temperature chaudiere est '},
'c4':{'name':'TKsoll',			    'unit':'°C',	'desc':'temperature chaudiere doit'},
'c5':{'name':'TRG',				    'unit':'°C',	'desc':'temperature fumees'},
'c6':{'name':'Taus',				'unit':'°C',	'desc':'temperature exterieur'},
'c7':{'name':'TA Gem.',			    'unit':'°C',	'desc':'temperature exterieur moyenne'},
'c8':{'name':'TPo',				    'unit':'°C',	'desc':'sonde BT haut'},
'c9':{'name':'TPm',				    'unit':'°C',	'desc':'sonde BT milieu'},
'c10':{'name':'TPu',				'unit':'°C',	'desc':'sonde BT bas'},
'c11':{'name':'TFW',				'unit':'°C',	'desc':'?'},
'c12':{'name':'TRL',				'unit':'°C',	'desc':'température retour est'},
'c13':{'name':'TRLsoll',     	 	'unit':'°C',	'desc':'température retour doit '},
'c14':{'name':'RLP',				'unit':'%',	    'desc':'?'},
'c15':{'name':'Tplat',			    'unit':'°C',	'desc':'Temp platine???'},
'c16':{'name':'TVL_A',			    'unit':'°C',	'desc':'?'},
'c17':{'name':'TVLs_A',			    'unit':'°C',	'desc':'?'},
'c18':{'name':'TRA',				'unit':'°C',	'desc':'?'},
'c19':{'name':'TBA',				'unit':'°C',	'desc':'?'},
'c20':{'name':'TBs_A',			    'unit':'°C',	'desc':'?'},
'c21':{'name':'TVL_1',			    'unit':'°C',	'desc':'temperature depart chauffage est '},
'c22':{'name':'TVL_2',			    'unit':'°C',	'desc':'?'},
'c23':{'name':'TVLs_1',			    'unit':'°C',	'desc':'temperature depart chauffage doit '},
'c24':{'name':'TVLs_2',			    'unit':'°C',	'desc':'?'},
'c25':{'name':'TR1',				'unit':'°C',	'desc':'?'},
'c26':{'name':'TR2',				'unit':'°C',	'desc':'?'},
'c27':{'name':'TB1',				'unit':'°C',	'desc':'temperature Ballon ECS est'},
'c28':{'name':'TBs_1',			    'unit':'°C',	'desc':'temperature Ballon ECS doit'},
'c29':{'name':'TVL_3',			    'unit':'°C',	'desc':'?'},
'c30':{'name':'TVL_4',			    'unit':'°C',	'desc':'?'},
'c31':{'name':'TVLs_3',			    'unit':'°C',	'desc':'?'},
'c32':{'name':'TVLs_4',			    'unit':'°C',	'desc':'?'},
'c33':{'name':'TR3',				'unit':'°C',	'desc':'?'},
'c34':{'name':'TR4',				'unit':'°C',	'desc':'?'},
'c35':{'name':'TB2',				'unit':'°C',	'desc':'?'},
'c36':{'name':'TBs_2',			    'unit':'°C',	'desc':'?'},
'c37':{'name':'TVL_5',			    'unit':'°C',	'desc':'?'},
'c38':{'name':'TVL_6',			    'unit':'°C',	'desc':'?'},
'c39':{'name':'TVLs_5',			    'unit':'°C',	'desc':'?'},
'c40':{'name':'TVLs_6',			    'unit':'°C',	'desc':'?'},
'c41':{'name':'TR5',				'unit':'°C',	'desc':'?'},
'c42':{'name':'TR6',				'unit':'°C',	'desc':'?'},
'c43':{'name':'TB3',				'unit':'°C',	'desc':'?'},
'c44':{'name':'TBs_3',			    'unit':'°C',	'desc':'?'},
'c45':{'name':'TRs_A',			    'unit':'°C',	'desc':'?'},
'c46':{'name':'TRs_1',			    'unit':'°C',	'desc':'?'},
'c47':{'name':'TRs_2',			    'unit':'°C',	'desc':'?'},
'c48':{'name':'TRs_3',			    'unit':'°C',	'desc':'?'},
'c49':{'name':'TRs_4',			    'unit':'°C',	'desc':'?'},
'c50':{'name':'TRs_5',			    'unit':'°C',	'desc':'?'},
'c51':{'name':'TRs_6',			    'unit':'°C',	'desc':'?'},
'c52':{'name':'SZs',				'unit':'%',	    'desc':'vitesse extracteur doit'},
'c53':{'name':'SZ',				    'unit':'%',	    'desc':'vitesse extracteur'},
'c54':{'name':'KeBrstScale',	    'unit':'%',	    'desc':'variable F'},
'c55':{'name':'ESRegler',   		'unit':'%',	    'desc':'?'},
'c56':{'name':'ESsoll',			    'unit':'%',	    'desc':'bois = %air(134) x %F(54) x %K(160)'},
'c57':{'name':'I Es',				'unit':'mA',	'desc':'conso vis bois'},
'c58':{'name':'I Ra',				'unit':'mA',	'desc':'pilotage vanne 3 voies 0 ou 3'},
'c59':{'name':'I Aa',				'unit':'mA',	'desc':'pilotage vanne 3 voies 0 ou 3'},
'c60':{'name':'I Sr',				'unit':'mA',	'desc':'conso nettoyeur/cendrier'},
'c61':{'name':'I Rein',			    'unit':'mA',	'desc':'conso nettoyeur/cendrier'},
'c62':{'name':'U_Lambda',			'unit':'mV',	'desc':'conso lambda'},
'c63':{'name':'MWZ Vorl.',		    'unit':'°C',	'desc':'?'},
'c64':{'name':'MWZ Rueckl.',		'unit':'°C',	'desc':'?'},
'c65':{'name':'MWZ Durchf.',		'unit':'',		'desc':'?'},
'c66':{'name':'MWZ Leist.', 		'unit':'KW',	'desc':'?'},
'c67':{'name':'VFS Flow',			'unit':'l/min', 'desc':'?'},
'c68':{'name':'VFS Temp',			'unit':'°C',	'desc':'?'},
'c69':{'name':'IO32 VL',			'unit':'°C',	'desc':'?'},
'c70':{'name':'SR motor',			'unit':'',		'desc':'moteur actionnement grille/ressort'},
'c71':{'name':'SRpos ist',  		'unit':'',		'desc':'selection grille ou ressort'},
'c72':{'name':'SR mode',			'unit':'',		'desc':'selection du sens de rotation du moteur'},
'c73':{'name':'KaskSollTmp_1',	    'unit':'°C',	'desc':'?'},
'c74':{'name':'KaskSollTmp_2',	    'unit':'°C',	'desc':'?'},
'c75':{'name':'KaskSollTmp_3',	    'unit':'°C',	'desc':'?'},
'c76':{'name':'KaskSollTmp_4',	    'unit':'°C',	'desc':'?'},
'c77':{'name':'KaskIstTmp_1',		'unit':'°C',	'desc':'?'},
'c78':{'name':'KaskIstTmp_2',		'unit':'°C',	'desc':'?'},
'c79':{'name':'KaskIstTmp_3',		'unit':'°C',	'desc':'?'},
'c80':{'name':'KaskIstTmp_4',		'unit':'°C',	'desc':'?'},
'c81':{'name':'UsePos',			    'unit':'',		'desc':'?'},
'c82':{'name':'UseMotSoll',		    'unit':'mm',	'desc':'?'},
'c83':{'name':'UseMotIst',		    'unit':'mm',	'desc':'?'},
'c84':{'name':'HKZustand_A',		'unit':'',		'desc':'?'},
'c85':{'name':'HKZustand_1',		'unit':'',		'desc':'mode de chauffage'},
'c86':{'name':'HKZustand_2',		'unit':'',		'desc':'?'},
'c87':{'name':'HKZustand_3',		'unit':'',		'desc':'?'},
'c88':{'name':'HKZustand_4',		'unit':'',		'desc':'?'},
'c89':{'name':'HKZustand_5',		'unit':'',		'desc':'?'},
'c90':{'name':'HKZustand_6',		'unit':'',		'desc':'?'},
'c91':{'name':'BoiZustand_A',		'unit':'',		'desc':'?'},
'c92':{'name':'BoiZustand_1',		'unit':'',		'desc':'Ballon ECS 0:off , 1:charge, 2:recyclage 	'},
'c93':{'name':'BoiZustand_2',		'unit':'',		'desc':'?'},
'c94':{'name':'BoiZustand_3',		'unit':'',		'desc':'?'},
'c95':{'name':'PuffZustand',		'unit':'',		'desc':'etat Tampon 3:charge 2:decharge	'},
'c96':{'name':'Puffer_soll',		'unit':'°C',	'desc':'Temp Tampon doit	'},
'c97':{'name':'Mode Fw',			'unit':'',		'desc':'erreur en cours :'},
'c98':{'name':'Einschubschn.BSZ',	'unit':'h',		'desc':'heures vis entree chaudiere '},
'c99':{'name':'Verbrauchszähler',	'unit':'Kg',	'desc':'kg	consommation pellet'},
'c100':{'name':'FRA Zustand',		'unit':'',		'desc':'	'},
'c101':{'name':'FR1 Zustand',		'unit':'',		'desc':'mode de commande'},
'c102':{'name':'FR2 Zustand',		'unit':'',		'desc':'	'},
'c103':{'name':'FR3 Zustand',		'unit':'',		'desc':'	'},
'c104':{'name':'FR4 Zustand',		'unit':'',		'desc':'	'},
'c105':{'name':'FR5 Zustand',		'unit':'',		'desc':'	'},
'c106':{'name':'FR6 Zustand',		'unit':'',		'desc':'	'},
'c107':{'name':'Ext.HK Soll',		'unit':'',		'desc':'	'},
'c108':{'name':'Ext.HK Soll_2',	    'unit':'',		'desc':'	'},
'c109':{'name':'Ext.HK Soll_3',	    'unit':'',		'desc':'	'},
'c110':{'name':'Höchste Anf',		'unit':'',		'desc':'temp depart chaudiere doit'},
'c111':{'name':'LZ LB seit Ent.',	'unit':'°C',	'desc':'temps combustion est (pour decendrage ?)'},
'c112':{'name':'LZ ES seit Füll.',  'unit':'',		'desc':'Min	temps vis pour aspiration est'},
'c113':{'name':'Anzahl Entasch.',	'unit':'',		'desc':'nombre decendrage'},
'c114':{'name':'Anzahl SR Beweg.',  'unit':'',		'desc':'mouvement grille'},
'c115':{'name':'Lagerstand',		'unit':'Kg',	'desc':'kg pellet restant'},
'c116':{'name':'KaskLZLeisMin_1',	'unit':'°C',	'desc':'?'},
'c117':{'name':'KaskLZLeisMin_2',	'unit':'°C',	'desc':'?'},
'c118':{'name':'KaskLZLeisMin_3',	'unit':'°C',	'desc':'?'},
'c119':{'name':'KaskLZLeisMin_4',	'unit':'°C',	'desc':'?'},
'c120':{'name':'KaskLZLeisMax_1',	'unit':'°C',	'desc':'?'},
'c121':{'name':'KaskLZLeisMax_2',	'unit':'°C',	'desc':'?'},
'c122':{'name':'KaskLZLeisMax_3',	'unit':'°C',	'desc':'?'},
'c123':{'name':'KaskLZLeisMax_4',	'unit':'°C',	'desc':'?'},
'c124':{'name':'Kask LZLeist_1',	'unit':'h',	    'desc':'?'},
'c125':{'name':'Kask LZLeist_2',	'unit':'h',	    'desc':'?'},
'c126':{'name':'Kask LZLeist_3',	'unit':'h',	    'desc':'?'},
'c127':{'name':'Kask LZLeist_4',	'unit':'h',	    'desc':'?'},
'c128':{'name':'AIN17',			    'unit':'V',	    'desc':'?'},
'c129':{'name':'BRT',				'unit':'°C',	'desc':'?'},
'c130':{'name':'IO32 522',		    'unit':'mV',	'desc':'?'},
'c131':{'name':'IO32 509',		    'unit':'mV',	'desc':'?'},
'c132':{'name':'IO32 510',		    'unit':'mV',	'desc':'?'},
'c133':{'name':'IO32 517',		    'unit':'°C',	'desc':'?'},
'c134':{'name':'Leistung',		    'unit':'%',	    'desc':'puissance '},
'c135':{'name':'KasEntaschFreigabe','unit':'',	    'desc':'?'},
'c136':{'name':'I_Lambda',   		'unit':'mA',	'desc':'intensite lambda'},
'c137':{'name':'TRA_A',			    'unit':'°C',	'desc':'?'},
'c138':{'name':'TRA_1',			    'unit':'°C',	'desc':'temperature interieur Z1 FR35'},
'c139':{'name':'TRA_2',			    'unit':'°C',	'desc':'?'},
'c140':{'name':'TRA_3',			    'unit':'°C',	'desc':'?'},
'c141':{'name':'TRA_4',			    'unit':'°C',	'desc':'?'},
'c142':{'name':'TRA_5',      		'unit':'°C',	'desc':'?'},
'c143':{'name':'TRA_6',      		'unit':'°C',	'desc':'?'},
'c144':{'name':'U_lambda_soll',	    'unit':'mV',	'desc':'tension lambda doit'},
'c145':{'name':'BRT Soll',		    'unit':'°C',	'desc':'?'},
'c146':{'name':'Anf. HKR1',		    'unit':'°C',	'desc':'?'},
'c147':{'name':'Anf. HKR2',		    'unit':'°C',	'desc':'?'},
'c148':{'name':'Anf. HKR3',		    'unit':'°C',	'desc':'?'},
'c149':{'name':'Anf. HKR4',		    'unit':'°C',	'desc':'?'},
'c150':{'name':'Anf. HKR5',		    'unit':'°C',	'desc':'?'},
'c151':{'name':'Anf. HKR6',		    'unit':'°C',	'desc':'?'},
'c152':{'name':'Anf. HKR7',		    'unit':'°C',	'desc':'?'},
'c153':{'name':'Anf. HKR8',		    'unit':'°C',	'desc':'?'},
'c154':{'name':'IO32 521',		    'unit':'mV',	'desc':'?'},
'c155':{'name':'BSZ_STEUERUNG',	    'unit':'h',	    'desc':'heures mise sous tension'},
'c156':{'name':'BSZ_HEIZUNG',		'unit':'h',	    'desc':'heures chauffage'},
'c157':{'name':'BSZ_ZUENDUNG',	    'unit':'h',	    'desc':'heures allumages'},
'c158':{'name':'BSZ_SZ',			'unit':'h',	    'desc':'heures extracteur fumées'},
'c159':{'name':'BSZ_AUSTRAG',		'unit':'h',	    'desc':'heures extracteur silo'},
'c160':{'name':'Regler K',		    'unit':'',		'desc':'regulateur : K'},
'c161':{'name':'BSZ_HEIZUNG_UPD',	'unit':'h',	    'desc':'heures chauffage upd'},
'c162':{'name':'BSZ_ZUENDUNGEN',	'unit':'',		'desc':'?'},
'c163':{'name':'BSZ_LEIST_90',	    'unit':'h',	    'desc':'heure puissance > 90%'},
'c164':{'name':'BSZ_GLUTERH',		'unit':'h',	    'desc':'veille /conservation braise ?'},
'c165':{'name':'UseSoll', 		    'unit':'mm',	'desc':'?'},
'c166':{'name':'UseIst', 			'unit':'mm',	'desc':'?'},
'c167':{'name':'UseStrom',		    'unit':'mA',	'desc':'?'},
'c168':{'name':'Anf. HKR0',		    'unit':'°C',	'desc':'?'},
'c169':{'name':'Anf. HKR9',		    'unit':'°C',	'desc':'?'},
'c170':{'name':'Anf. HKR10',		'unit':'°C',	'desc':'?'},
'c171':{'name':'Anf. HKR11',		'unit':'°C',	'desc':'?'},
'c172':{'name':'Anf. HKR12',		'unit':'°C',	'desc':'?'},
'c173':{'name':'Anf. HKR13',		'unit':'°C',	'desc':'?'},
'c174':{'name':'Anf. HKR14',		'unit':'°C',	'desc':'?'},
'c175':{'name':'Anf. HKR15',		'unit':'°C',	'desc':'?'},
'c176':{'name':'Spreizung',		    'unit':'°C',	'desc':'?'},
'c177':{'name':'max.Leist.P3F.HT',  'unit':'%',	    'desc':'?'},
'c178':{'name':'TPmo',			    'unit':'°C',	'desc':'?'},
'c179':{'name':'TPmu',			    'unit':'°C',	'desc':'?'},
'c180':{'name':'Puff Füllgrad',	    'unit':'%',	    'desc':'remplissage du Ballon Tampon'},
'c181':{'name':'?',				    'unit':'',		'desc':'?'},
'c182':{'name':'?',				    'unit':'',		'desc':'?'},
'c183':{'name':'?',				    'unit':'',		'desc':'?'},
'c184':{'name':'?',				    'unit':'',		'desc':'?'},
'c185':{'name':'?',				    'unit':'',		'desc':'?'},
'c186':{'name':'?',				    'unit':'',		'desc':'?'},
'c187':{'name':'?',				    'unit':'',		'desc':'?'},
'c188':{'name':'?',				    'unit':'',		'desc':'?'},

        }
        #todo manage different maps depending on firmware version
        self.map = {
			 0 :'c0'  ,  1:'c1'  ,  2:'c2'  ,  3:'c3'  ,  4:'c4'  ,  5:'c12' ,  6:'c13' ,  7:'c176',  8:'c5'  ,  9:'c53',
			10 :'c52' , 11:'c8'  , 12:'c9'  , 13:'c10' , 14:'c180', 15:'c96' , 16:'c106', 17:'c95' , 18:'c110', 19:'c11',
			20 :'c134', 21:'c56' , 22:'c48' , 23:'c49' , 24:'c50' , 25:'c51' , 26:'c55' , 27:'c160', 28:'c54' , 29:'c121',
			30 :'c97' , 31:'c57' , 32:'c58' , 33:'c59' , 34:'c60' , 35:'c61' , 36:'c112', 37:'c111', 38:'c113', 39:'c114',
			40 :'c115', 41:'c99' , 42:'c154', 43:'c130', 44:'c136', 45:'c62' , 46:'c79' , 47:'c73' , 48:'c129', 49:'c15',
			50 :'c76' , 51:'c119', 52:'c128', 53:'c6'  , 54:'c7'  , 55:'c107', 56:'c16' , 57:'c17' , 58:'c137', 59:'c45',
			60 :'c84' , 61:'c100', 62:'c21' , 63:'c23' , 64:'c138', 65:'c46' , 66:'c85' , 67:'c101', 68:'c22' , 69:'c24',
			70 :'c139', 71:'c47' , 72:'c86' , 73:'c102', 74:'c120', 75:'c41' , 76:'c187', 77:'c42' , 78:'c186', 79:'c188',
			80 :'c19' , 81:'c20' , 82:'c27' , 83:'c28' , 84:'c92' , 85:'c80' , 86:'c118', 87:'c145', 88:'c168', 89:'c146',
			90 :'c147', 91:'c148', 92:'c149', 93:'c150', 94:'c151', 95:'c152', 96:'c153', 97:'c169', 98:'c170', 99:'c171',
			100:'c172',101:'c173',102:'c174',103:'c182',104:'c181' ,105:'c165',106:'c166',107:'c167'
        }
